// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjiuM_L0pi4SThtI_8GQR3EsbBqQV-th8',
    appId: '1:211304453423:web:e87b58cf28d30f90793dda',
    messagingSenderId: '211304453423',
    projectId: 'flutter-project-bfbc5',
    authDomain: 'flutter-project-bfbc5.firebaseapp.com',
    storageBucket: 'flutter-project-bfbc5.firebasestorage.app',
    measurementId: 'G-8SHEYL7F49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi-JCVpixPf_6IFytZr3GvpoEdeobpENE',
    appId: '1:211304453423:android:989a52e78a6e8065793dda',
    messagingSenderId: '211304453423',
    projectId: 'flutter-project-bfbc5',
    storageBucket: 'flutter-project-bfbc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxWtY9-yXtTy_11WJ6oOen1Jqd7uJ1HAU',
    appId: '1:211304453423:ios:9245138ad8d2d2d8793dda',
    messagingSenderId: '211304453423',
    projectId: 'flutter-project-bfbc5',
    storageBucket: 'flutter-project-bfbc5.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxWtY9-yXtTy_11WJ6oOen1Jqd7uJ1HAU',
    appId: '1:211304453423:ios:9245138ad8d2d2d8793dda',
    messagingSenderId: '211304453423',
    projectId: 'flutter-project-bfbc5',
    storageBucket: 'flutter-project-bfbc5.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjiuM_L0pi4SThtI_8GQR3EsbBqQV-th8',
    appId: '1:211304453423:web:0e6689c9e852cc99793dda',
    messagingSenderId: '211304453423',
    projectId: 'flutter-project-bfbc5',
    authDomain: 'flutter-project-bfbc5.firebaseapp.com',
    storageBucket: 'flutter-project-bfbc5.firebasestorage.app',
    measurementId: 'G-047QR7WCRB',
  );
}
